1. Importing libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import pickle

2. Connecting dataset

In [2]:
df = pd.read_csv(
    "/content/diabetes_prediction_dataset.csv"
)


df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

3. Understanding dataset

In [3]:
df.shape

(100000, 9)

In [4]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

4. Seperate features and target

In [5]:
X = df.drop(
    "diabetes",
    axis=1
)


y = df["diabetes"]

5. Encoding categorical columns

In [6]:
gender_encoder = LabelEncoder()

smoking_encoder = LabelEncoder()

X["gender"] = gender_encoder.fit_transform(
    X["gender"]
)


X["smoking_history"] = smoking_encoder.fit_transform(
    X["smoking_history"]
)
X.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,1,4,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,0,4,27.32,5.7,158
3,0,36.0,0,0,1,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155

6. Train Test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

7. Feature scaling

In [8]:
scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(
    X_train
)


X_test_scaled = scaler.transform(
    X_test
)

8. Model Training

In [9]:
model = RandomForestClassifier(

    n_estimators=200,

    max_depth=10,

    random_state=42

)
model = RandomForestClassifier(

    n_estimators=200,

    max_depth=10,

    random_state=42

)

9. Prediction

In [11]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(
    X_test_scaled
)

10. Evaluation

In [12]:
accuracy = accuracy_score(
    y_test,
    y_pred
)


print(
    "Accuracy:",
    accuracy
)

Accuracy: 0.97225

11. Classification report

In [13]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.97      1.00      0.99     18300
           1       1.00      0.67      0.81      1700

    accuracy                           0.97     20000
   macro avg       0.98      0.84      0.90     20000
weighted avg       0.97      0.97      0.97     20000

12. Confusion Matrix

In [14]:
confusion_matrix(
    y_test,
    y_pred
)

array([[18299,     1],
       [  554,  1146]])

13. Saving the models

In [16]:
import os

os.makedirs(
    "models",
    exist_ok=True
)
pickle.dump(

    model,

    open(
        "models/diabetes_model.pkl",
        "wb"
    )

)

14. Saving scaler

In [20]:
pickle.dump(

    scaler,

    open(
        "models/diabetes_scaler.pkl",
        "wb"
    )

)

15. Saving Encoders

In [19]:
pickle.dump(
    gender_encoder,

    open(
        "models/gender_encoder.pkl",
        "wb"
    )
)

pickle.dump(

    smoking_encoder,

    open(
        "models/smoking_encoder.pkl",
        "wb"
    )

)

**Model Accuracy ~ 97%**